openapi: 3.0.0
info:
  title: PhpStorm 2020.2
  description: PhpStorm 2020.2 Demo API
  version: 1.0.0
servers:
  - url: http://phpstorm.localhost
paths:
  /whatsnew:
    get:
      responses:
        200:
          description: List of all new features.
